// The known answers of SSKR that a self-test compares with: the official BCR-2020-011 grouped
// vector, its shares written as colours, and the secret they restore. A host checks its own SSKR
// library with them before it trusts it with a secret.
//
// From the host it needs only its SharePlatform (share-platform.ts), whose combineShares restores
// the vector. It holds public test data, no secret.
//
// Host-neutral: it imports only other host-neutral sskr modules (test/portable-modules.test.ts).

import type { SharePlatform } from "./share-platform.js";
import { colorsToShare, normalizeShare, shareToColors } from "./transport.js";

// Official BCR-2020-011 grouped vector, not a secret generated by this implementation.
export const sskrVector = {
  entropy: "7daa851251002874e1a1995f0897e6b1",
  // Computed independently from published raw bytes using Python zlib CRC32 for the checksum
  // and the mixing (src/sskr/transport.ts, shareMask).
  firstShareColors: [
    "#41C47E",
    "#42D1F0",
    "#0981D6",
    "#EE44D3",
    "#7C4D62",
    "#E75FF8",
    "#955228",
    "#F02D9B",
    "#CADD22",
    "#670000",
  ],
  // The same share as MnemoCode writes it in BIP39 word numbers, counted from 1, and in the
  // Unicode codes of those words (transport.ts, version A2), as typed, separated by spaces:
  // computed independently in the same way, with the BIP39 Traditional Chinese word list.
  firstShareNumbers:
    "527 288 1158 1328 5 1544 734 1605 1692 1812 710 1654 2045 598 582 241 365 1779 1467 551 897",
  firstShareUnicode:
    "9805 968E 70AE 555F 4E0D 7642 6751 7686 7709 75C7 5354 77FD 97CB 964D 670D 5E7E 7FA4 5410 4EF2 6CB3 5BEC",
  shares: [
    "ur:sskr/gogrrsbyadaefmnlbnctaaecvoqdfnjpbzecstfgaxtifpsskbfw",
    "ur:sskr/gogrrsbyadaohtrygabavahphnlrlpmkghwyiojkjtkpmdkncfjp",
    "ur:sskr/gogrrsbybgaefywsfefhiymofseyihfremkivwsogrespmclwepd",
    "ur:sskr/gogrrsbybgaootkoehgoztzcreloknrfvawyinssrksnmedtfmks",
    "ur:sskr/gogrrsbybgaaiaeenbuyksetonswsstduoprvwrphkbytlfzlyca",
  ],
} as const;

/**
 * A set of one group, two of three shares needed (vectors/sskr-v1.json, "bip39-128-2-of-3"),
 * written by the pinned SSKR library, which restores the official vector above, from the entropy
 * 000102…0f; the colors of its first two shares; and the BIP39 phrase of that entropy, computed
 * independently with Python's hashlib. The share self-tests repair and check it.
 */
export const sskrSetVector = {
  shares: [
    "ur:sskr/goemjzaeadaejoinoyvotkwlptsskispvwbkbwjnamstlubnampf",
    "ur:sskr/goemjzaeadadflihpkmhspcheycndschfhcmkelyvaveiesolrls",
    "ur:sskr/goemjzaeadaockjsrlamsebalrbysbjngeeysnplutlywdfytpwe",
  ],
  colors: [
    "#8B0C06 #B0D4F5 #0CF800 #FA41D6 #37B8CA #1F9121 #DB206C #4FD8A1 #1BF322 #750000",
    "#64C984 #835170 #897D85 #7FC452 #853144 #E8135A #C542B2 #158738 #F19A47 #D30000",
  ],
  phrase: "abandon amount liar amount expire adjust cage candy arch gather drum buyer",
} as const;

/**
 * Compares the colour transport and the host's SSKR library with the known answers; throws, before
 * any secret is touched, at the first difference.
 */
export async function checkSskrKnownAnswers(platform: SharePlatform): Promise<void> {
  if (
    shareToColors(sskrVector.shares[0]).join(" ") !== sskrVector.firstShareColors.join(" ") ||
    colorsToShare(sskrVector.firstShareColors.join(" ")) !== sskrVector.shares[0]
  ) {
    throw new Error("SSKR color known-answer self-test failed. No secret was processed.");
  }
  for (const share of sskrVector.shares) {
    if (colorsToShare(shareToColors(share).join("")) !== normalizeShare(share))
      throw new Error("SSKR color self-test failed. No secret was processed.");
  }
  const restored = await platform.combineShares(sskrVector.shares);
  try {
    if (
      Array.from(restored, (byte) => byte.toString(16).padStart(2, "0")).join("") !==
      sskrVector.entropy
    )
      throw new Error("SSKR recovery self-test failed. No secret was processed.");
  } finally {
    restored.fill(0);
  }
}
