import { sskrEngine } from "./runtime.js";
import { colorsToShare, normalizeShare, shareToColors } from "./transport.js";

// Official BCR-2020-011 grouped vector, not a secret generated by this implementation.
export const sskrVector = {
  entropy: "7daa851251002874e1a1995f0897e6b1",
  // Computed independently from published raw bytes using Python zlib CRC32 for the checksum
  // and the mixing (src/sskr/transport.ts, shareMask).
  firstShareColors: [
    "#41C47E",
    "#42D1F0",
    "#0981D6",
    "#EE44D3",
    "#7C4D62",
    "#E75FF8",
    "#955228",
    "#F02D9B",
    "#CADD22",
    "#670000",
  ],
  shares: [
    "ur:sskr/gogrrsbyadaefmnlbnctaaecvoqdfnjpbzecstfgaxtifpsskbfw",
    "ur:sskr/gogrrsbyadaohtrygabavahphnlrlpmkghwyiojkjtkpmdkncfjp",
    "ur:sskr/gogrrsbybgaefywsfefhiymofseyihfremkivwsogrespmclwepd",
    "ur:sskr/gogrrsbybgaootkoehgoztzcreloknrfvawyinssrksnmedtfmks",
    "ur:sskr/gogrrsbybgaaiaeenbuyksetonswsstduoprvwrphkbytlfzlyca",
  ],
} as const;

let passed = false;
export async function assertSskrSelfTest(): Promise<void> {
  if (passed) return;
  const engine = await sskrEngine();
  if (
    shareToColors(sskrVector.shares[0]).join(" ") !== sskrVector.firstShareColors.join(" ") ||
    colorsToShare(sskrVector.firstShareColors.join(" ")) !== sskrVector.shares[0]
  ) {
    throw new Error("SSKR color known-answer self-test failed. No secret was processed.");
  }
  for (const share of sskrVector.shares) {
    if (colorsToShare(shareToColors(share).join("")) !== normalizeShare(share))
      throw new Error("SSKR color self-test failed. No secret was processed.");
  }
  const restored = engine.recover_sskr_shares(sskrVector.shares.join("\n"));
  try {
    if (
      Array.from(restored, (byte) => byte.toString(16).padStart(2, "0")).join("") !==
      sskrVector.entropy
    )
      throw new Error("SSKR recovery self-test failed. No secret was processed.");
  } finally {
    restored.fill(0);
  }
  passed = true;
}
